service: fetchData # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  role: arn:aws:iam::473632466360:role/lambda-stock-price-readwrite

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - .pytest_cache/**
    - .serverless/**
    - .vscode/**
    - __pycache__/**
    - env/**
    - symbols_short.csv
    - symbols.csv

functions:
  main:
    handler: fetchData.main

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
